spring:
  datasource:
    url: jdbc:postgresql://localhost/shlink
    username: postgres
    password: postgres
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yml
    default-schema: public
server:
  port: 443
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:keystore/websock.p12
    key-store-password: 123654
    key-alias: cert_2
    key-password: 123654
jwt:
  secret: mykey
hostname: localhost
